# Версия синтаксиса docker compose.
version: '3.8'

# В этом разделе мы определяем все сервисы (контейнеры),
# которые необходимы для работы нашего приложения.
services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: vegshare
      POSTGRES_PASSWORD: vegshare
      POSTGRES_HOST_AUTH_METHOD: scram-sha-256
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - vegshare-net

  redis:
    image: redis:7.2
    ports:
      - "6379:6379"
    restart: unless-stopped
    networks:
      - vegshare-net

  rabbitmq:
    image: rabbitmq:3-management
    hostname: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq/
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - vegshare-net

  mediamtx:
    image: bluenviron/mediamtx:latest
    ports:
      - "8554:8554"      # RTSP
      - "8888:8888"      # HLS (HTTP)
      - "8889:8889"      # WebRTC (WebSocket)
      - "1935:1935"      # RTMP
      - "8189:8189/udp"  # WebRTC (UDP)
      - "9997:9997"      # API
    volumes:
      - ./mediamtx.yml:/mediamtx.yml
    environment:
      - MTX_CONF_PATH=/mediamtx.yml
    restart: unless-stopped
    networks:
      - vegshare-net

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: unless-stopped
    volumes:
      - ./backend/configs/config-docker.yaml:/app/configs/config.yaml
    depends_on:
      postgres:
        condition: service_started
      redis:
        condition: service_started
      rabbitmq:
        condition: service_healthy
    networks:
      - vegshare-net

  backend-worker:
    build:
      context: ./backend
      dockerfile: Dockerfile.worker
    restart: unless-stopped
    volumes:
      - ./backend/configs/config-docker.yaml:/app/configs/config.yaml
    depends_on:
      postgres:
        condition: service_started
      redis:
        condition: service_started
      rabbitmq:
        condition: service_healthy
    networks:
      - vegshare-net

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:80"
    restart: unless-stopped
    depends_on:
      backend:
        condition: service_started
    environment:
      - VITE_WEBSOCKET_URL=ws://mediamtx:8889
    networks:
      - vegshare-net

volumes:
  pg_data:
  rabbitmq_data:

networks:
  vegshare-net: