version: '3.8'

services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: vegshare
      POSTGRES_PASSWORD: vegshare
      POSTGRES_HOST_AUTH_METHOD: scram-sha-256
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:7.2
    ports:
      - "6379:6379"
    restart: unless-stopped

volumes:
  pg_data:

