http:
  host: "0.0.0.0"       # Хост
  port: "8080"          # Порт сервера


database:
  host: "postgres"
  port: 5432
  user: "vegshare"
  dbname: "vegshare"
  password: "vegshare"
  sslmode: "disable"
#  max_connections: 10
#  timeout: 5s
#  url: "postgres://vegshare:vegshare@postgres:5432/db?sslmode=disable"

jwt:
  secret: "my_super_secret_key" # Секретный ключ для подписи токенов
  access_token_ttl: "8h"  # 8 часов
  refresh_token_ttl: "168h" # 7 дней

redis:
  url: "redis://redis:6379"
  ttl: 3600             # TTL кеша в секундах

rabbitmq:
  url: "amqp://guest:guest@rabbitmq:5672/"